[package]
name = "tictactoe"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
# macroquad = "0.4.13"
owo-colors = "4.1.0"
rand = "0.8.5"
tabled = "0.17.0"
text_io = "0.1.12"
